import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { client } from 'utils';
import { Layout } from 'components/layouts';
import { BlogPost } from 'interfaces';
import { BlogCard } from 'components/ui';
import { Grid } from '@nextui-org/react';

interface HomeProps {
  posts: BlogPost[];
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  console.log(posts);

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Grid.Container gap={2} justify='center'>
          {posts.map(post => (
            <Grid xs={12} sm={6} md={6} lg={4} key={post.slug}>
              <BlogCard post={post} />
            </Grid>
          ))}
        </Grid.Container>
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const response = await client.getEntries({
    content_type: 'blogPost-2',
  });

  return {
    props: {
      posts: response.items.map(item => Object.assign({}, item.fields)),
    },
  };
};

export default Home;
